version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - app
    networks:
      - laravel_network

  postgres:
    build:
      context: .docker/postgres
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - laravel_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  laravel_network:
    driver: bridge
