services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - new_postgres
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  new_postgres:
    image: postgres:17
    container_name: laravel_new_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: my_new_db
      POSTGRES_USER: new_laravel_user
      POSTGRES_PASSWORD: my_user
    ports:
      - "5435:5432"
    networks:
      - laravel_network
    volumes:
      - new_postgres_data:/var/lib/postgresql/data

volumes:
  new_postgres_data:

networks:
  laravel_network:
    driver: bridge
